-- Rollback SQL Script for NexAgent Prisma Schema

DROP TABLE IF EXISTS "Settings" CASCADE;
DROP TABLE IF EXISTS "KBEntry" CASCADE;
DROP TABLE IF EXISTS "AuditLog" CASCADE;
DROP TABLE IF EXISTS "HumanOverride" CASCADE;
DROP TABLE IF EXISTS "Decision" CASCADE;
DROP TABLE IF EXISTS "StepLog" CASCADE;
DROP TABLE IF EXISTS "PipelineRun" CASCADE;
DROP TABLE IF EXISTS "Ticket" CASCADE;
DROP TABLE IF EXISTS "Category" CASCADE;
DROP TABLE IF EXISTS "User" CASCADE;

DROP TYPE IF EXISTS "Role";
DROP TYPE IF EXISTS "PipelineType";
DROP TYPE IF EXISTS "PipelineStatus";
DROP TYPE IF EXISTS "StepStatus";
DROP TYPE IF EXISTS "DecisionOutcome";
